name: Andrew Logan
favicon: null
layout_spectrum: 0.7755268793553114
typography_spectrum: 0.4995942150708288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7ab7e0'
    - '#0083c1'
    - '#3c3437'
    - '#476925'
    - '#fce9d5'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
